### ISSUE TITLE
Fatal crash

### ISSUE THREAD

**Issue by moonheart08** [devfacet/weather#4]
When searching something that throws an error, and then searching . or *, the package crashes

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> TypeError: Cannot read property 'weatherdata' of null
>     at C:\node\node_modules\weather-js\lib\weather.js:50:23
>     at Parser.<anonymous> (C:\node\node_modules\weather-js\node_modules\xml2js\l
> ib\xml2js.js:489:18)
>     at emitOne (events.js:77:13)
>     at Parser.emit (events.js:169:7)
>     at Object.onend (C:\node\node_modules\weather-js\node_modules\xml2js\lib\xml
> 2js.js:319:26)
>     at emit (C:\node\node_modules\weather-js\node_modules\xml2js\node_modules\sa
> x\lib\sax.js:640:35)
>     at end (C:\node\node_modules\weather-js\node_modules\xml2js\node_modules\sax
> \lib\sax.js:683:5)
>     at Object.write (C:\node\node_modules\weather-js\node_modules\xml2js\node_mo
> dules\sax\lib\sax.js:991:14)
>     at Object.SAXParser.close (C:\node\node_modules\weather-js\node_modules\xml2
> js\node_modules\sax\lib\sax.js:157:38)
>     at Parser.exports.Parser.Parser.parseString (C:\node\node_modules\weather-js
> \node_modules\xml2js\lib\xml2js.js:508:42)

**Comment by M4GNV5** [comment]
dump, have the same problem:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'weatherdata' of null
    at /home/work/hackbot/node_modules/weather-js/lib/weather.js:50:23
    at Parser.<anonymous> (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Object.onend (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/lib/xml2js.js:316:26)
    at emit (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/node_modules/sax/lib/sax.js:639:35)
    at end (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/node_modules/sax/lib/sax.js:682:5)
    at Object.write (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/node_modules/sax/lib/sax.js:981:14)
    at Object.SAXParser.close (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/node_modules/sax/lib/sax.js:156:38)
    at Parser.exports.Parser.Parser.parseString (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/lib/xml2js.js:502:42)
    at Parser.parseString (/home/work/hackbot/node_modules/weather-js/node_modules/xml2js/lib/xml2js.js:7:59)
    at Request._callback (/home/work/hackbot/node_modules/weather-js/lib/weather.js:47:17)
    at Request.self.callback (/home/work/hackbot/node_modules/request/request.js:198:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/work/hackbot/node_modules/request/request.js:1035:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/home/work/hackbot/node_modules/request/request.js:962:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
```

**Comment by devfacet** [comment]
Fixed by https://github.com/devfacet/weather/commit/7bc3787ad6a23125742e28120c59318a229b6565

**Comment by phouthasak** [comment]
I am still having the same problem as mention by the above 2 users.
